services:
  #Consul
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    command: agent -server -bootstrap -ui -client=0.0.0.0 -log-level=err
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8500/v1/status/leader" ]
      timeout: 5s
      retries: 10
    networks:
      - backend

  #MySQL
  mysql-quiz:
    image: mysql:8.0
    container_name: mysql_quiz
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: quizdb
    ports:
      - "3307:3306"
    volumes:
      - quiz_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    networks:
      - backend

  mysql-question:
    image: mysql:8.0
    container_name: mysql_question
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: questiondb
    ports:
      - "3308:3306"
    volumes:
      - question_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    networks:
      - backend

  mysql-result:
    image: mysql:8.0
    container_name: mysql_result
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: resultdb
    ports:
      - "3309:3306"
    volumes:
      - result_db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
    networks:
      - backend

  #RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      timeout: 5s
      retries: 5
    networks:
      - backend

  #Gateway
  gateway:
    build:
      context: ../backend/gateway
      dockerfile: Dockerfile
    container_name: gateway
    image: gateway:latest
    environment:
      - SPRING_CLOUD_CONSUL_HOST=${SPRING_CLOUD_CONSUL_HOST}
      - SPRING_CLOUD_CONSUL_PORT=${SPRING_CLOUD_CONSUL_PORT}
      - SERVER_PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - consul
      - quiz
    networks:
      - backend
      - frontend

  #Backend Services
  quiz:
    build:
      context: ../backend/quiz
      dockerfile: Dockerfile
    container_name: quiz
    image: quiz:latest
    environment:
      - SPRING_CLOUD_CONSUL_HOST=${SPRING_CLOUD_CONSUL_HOST}
      - SPRING_CLOUD_CONSUL_PORT=${SPRING_CLOUD_CONSUL_PORT}
      - DB_URL_QUIZ=${DB_URL_QUIZ}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      consul:
        condition: service_healthy
      mysql-quiz:
        condition: service_healthy
    networks:
      - backend

  question:
    build:
      context: ../backend/question
      dockerfile: Dockerfile
    container_name: question
    image: question:latest
    environment:
      - SPRING_CLOUD_CONSUL_HOST=${SPRING_CLOUD_CONSUL_HOST}
      - SPRING_CLOUD_CONSUL_PORT=${SPRING_CLOUD_CONSUL_PORT}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - DB_URL_QUESTION=${DB_URL_QUESTION}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      consul:
        condition: service_healthy
      mysql-question:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - backend

  result:
    build:
      context: ../backend/result
      dockerfile: Dockerfile
    container_name: result
    image: result:latest
    environment:
      - SPRING_CLOUD_CONSUL_HOST=${SPRING_CLOUD_CONSUL_HOST}
      - SPRING_CLOUD_CONSUL_PORT=${SPRING_CLOUD_CONSUL_PORT}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - DB_URL_RESULT=${DB_URL_RESULT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      consul:
        condition: service_healthy
      mysql-result:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - backend

  ai:
    build:
      context: ../backend/ai
      dockerfile: Dockerfile
    container_name: ai
    image: ai:latest
    environment:
      - SPRING_CLOUD_CONSUL_HOST=${SPRING_CLOUD_CONSUL_HOST}
      - SPRING_CLOUD_CONSUL_PORT=${SPRING_CLOUD_CONSUL_PORT}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_URL=${OPENAI_API_URL}
    depends_on:
      consul:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - backend

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend
    image: frontend:latest
    environment:
      - VITE_API_URL=http://gateway:8000
    ports:
      - "3000:80"
    depends_on:
      - gateway
    networks:
      - frontend

volumes:
  quiz_db_data:
  question_db_data:
  result_db_data:

networks:
  backend:
  frontend: