version: "3.8"

services:
  mysql-quiz:
    image: mysql:8.0
    container_name: mysql_quiz
    env_file:
      - ../backend/quiz/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: quizdb
    ports:
      - "3307:3306"
    volumes:
      - quiz_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  mysql-question:
    image: mysql:8.0
    container_name: mysql_question
    env_file:
      - ../backend/question/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: questiondb
    ports:
      - "3308:3306"
    volumes:
      - question_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  mysql-result:
    image: mysql:8.0
    container_name: mysql_result
    env_file:
      - ../backend/result/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: resultdb
    ports:
      - "3309:3306"
    volumes:
      - result_db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      timeout: 5s
      retries: 5

  quiz:
    build:
      context: ../backend/quiz
      dockerfile: Dockerfile
    container_name: quiz
    image: quiz:latest
    env_file:
      - ../backend/quiz/.env
    environment:
      - SPRING_CLOUD_CONSUL_ENABLED=false
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      mysql-quiz:
        condition: service_healthy

  question:
    build:
      context: ../backend/question
      dockerfile: Dockerfile
    container_name: question
    image: question:latest
    env_file:
      - ../backend/question/.env
    environment:
      - SPRING_CLOUD_CONSUL_ENABLED=false
      - SERVER_PORT=8081
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    ports:
      - "8081:8081"
    depends_on:
      mysql-question:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  result:
    build:
      context: ../backend/result
      dockerfile: Dockerfile
    container_name: result
    image: result:latest
    env_file:
      - ../backend/result/.env
    environment:
      - SPRING_CLOUD_CONSUL_ENABLED=false
      - SERVER_PORT=8082
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    ports:
      - "8082:8082"
    depends_on:
      mysql-result:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  ai:
    build:
      context: ../backend/ai
      dockerfile: Dockerfile
    container_name: ai
    image: ai:latest
    env_file:
      - ../backend/ai/.env
    environment:
      - SPRING_CLOUD_CONSUL_ENABLED=false
      - SERVER_PORT=8083
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    ports:
      - "8083:8083"
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  quiz_db_data:
  question_db_data:
  result_db_data:
